calError <- function(ccc){
  msg <- "calculated by calError()"

  a <- abbrevList(ccc)

  IND <- getSubList(a$cm, "p_ind")
  OFS <- getSubList(a$cm, "p_ind_offset")

  if(is.null(IND)){
    IND <- getSubList(a$cm, "ind")
  }
  
  if(is.null(OFS)){
    OFS <- getSubList(a$cm, "ind_offset")
  }
  
  if(is.null(OFS)){
    OFS <- getSubList(a$cm, "offset")
  }

  CAL <- getSubList(a$ca, "cal")

  ## get conv function schreiben!
  ## done!
  convInd <- getConvFactor(ccc, CAL,IND)
  convOfs <- getConvFactor(ccc, CAL,OFS)

  ind <- getConstVal(NA,NA,IND) * convInd
  ofs <- getConstVal(NA,NA,OFS) * convOfs

  ## unit of ind and offset is now
  indUnit <- CAL$Unit

  msg <- paste(msg,
               "ind conversion factor was:", convInd,
               "offset conversion factor was:",convOfs )

  ind  <- checkOutIndex(a,ind)
  ofs  <- checkOutIndex(a,ofs)


  cal <- getConstVal(NA,NA,CAL)

  corrind <- (ind - ofs)


  error <- corrind/cal - 1

  ccc$Calibration$Analysis$Values$Pressure <-
    setCcl(ccc$Calibration$Analysis$Values$Pressure, "ind",
           indUnit,
           ind,
           paste(msg)
           )

  ccc$Calibration$Analysis$Values$Pressure <-
    setCcl(ccc$Calibration$Analysis$Values$Pressure, "offset",
           indUnit,
           ofs,
           paste(msg)
           )

  ccc$Calibration$Analysis$Values$Pressure <-
    setCcl(ccc$Calibration$Analysis$Values$Pressure, "corrind",
           indUnit,
           corrind,
           paste(msg, ";p_ind - p_ind_offset")
           )

  ccc$Calibration$Analysis$Values$Error <-
    setCcl(ccc$Calibration$Analysis$Values$Error, "relative",
           "1",
           error,
           paste(msg, "error is defined by (corrind/p_cal-1), Unit is generated by getConvFactor(ccc, CAL,IND)/CAL$UNIT")
           )

  return(ccc)
}
