refreshCustomerCalibrationObject <- function(cdb,ccc){
  ## laut Vereinbarung ist das erste CO immer das
  ## Kundengerät !
  a <- abbrevList(ccc)

  a$cmco <- a$cmco
  noOfCo <- length(a$cmco)

### 1.)
  if(noOfCo == 1 ){
    ## dann möglicherweise ein id Eintrag:
    if(length(a$cmco$id) == 1){
      ## zweig ersetzt eine unter CO vorkommende id
      ## durch das entsprechende Object.
      ##
      ## wenn also unter CO eine id steht
      ## (length(a$cmco$id) == 1)
      ## dann ersetze die id durch das
      ## CalibrationObject aus der couch
      cdb$id <- a$cmco$id
      CAresponse <-   cdbGetDoc(cdb)$res
      ## wenn es das gibt ...
      if(length(CAresponse$CalibrationObject) > 0){
        ## ... dann reinbasteln
        ccc$Calibration$Measurement$CalibrationObject[[1]] <- CAresponse$CalibrationObject
      }
    }
  }

###2.)
  if(noOfCo == 0  ){
    ## es gibt noch kein CalibrationObject
    sCo <-  list(
                 Comment ="generated by updateCalOb",
                 Date    = list(
                   Type="generated",
                   Value= toString(format(Sys.time(), "%Y-%m-%d %H:%M" ) )
                   )
                 )
    ## es gibt noch kein Kunden CO -> sCo wird zum Kunden CO
    ccc$Calibration$Measurement$CalibrationObject[[1]] <-sCo
  }
  return(ccc)

}
